apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 2
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: payment:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080