apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 2
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: barna03/order-repo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8