apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 2
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: product:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
  
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: order-app-config
                  key: db_url
  
            - name: DB_PORT
              value: "3306"
  
            - name: SERVER_PORT
              value: "8081"
  
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: productdb-config
                  key: dbName
  
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: username
  
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: productdb-secrets
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  externalIPs:
    - 1.2.4.120


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-app-config
data:
  db_url: prdouct-db-service
  topic-name: topic

---
apiVersion: v1
kind: Secret
metadata:
  name: product-app-secret
type: Opaque
stringData:
  username: cm9vdA==
  password: MTk4Ng==
